site_name: jod35' blog
site_description: an example blog set up following the blog tutorials
site_url: http://jod35.github.io/site

nav:
  - jod35: index.md
  - Projects: 
    - Index: projects/index.md
  - Blog: blog/index.md
  - Talks: talks/index.md

extra_css:
  - assets/styles.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      options:
        custom_icons:
          - theme/.icons
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition

theme:
  name: material
  logo: imgs/me.png
  custom_dir: overrides
  font:
    text: Jetbrains Mono
  features:
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.code.annotate 

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: #68bff3 
      accent: #68BFF3
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: #68bff3 
      accent: #68BFF3
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jod35
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@SsaliJonathan
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jod35/
    - icon: fontawesome/brands/twitter
      ink: https://www.x.com/jod35/

  analytics:
    provider: google
    property: G-XXBR69YQH3
           
plugins:
   - glightbox
   - search
   - blog
   - tags
   - macros

blog:
  - archive_date_format: MMMM yyyy
    authors_profiles: true
    pagination_per_page: 5
   
repo_name: jod35/jod35.github.io
repo_url: https://github.com/jod35/jod35.github.io
copyright: ⓒ 2024 - <script>document.write(new Date().getFullYear())</script> Ssali Jonathan. 
